version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

  jobs:
    pre_build:
      - mkdir -p $HOME/.ploomber/stats/
      - echo "version_check_enabled: false" >> $HOME/.ploomber/stats/config.yaml
    post_create_environment:
      - "conda env export"

conda:
  environment: doc/environment.yml

sphinx:
  builder: html
  fail_on_warning: true
