from pkgmt.github import get_repo_and_branch_for_readthedocs

repository_url, repository_branch = get_repo_and_branch_for_readthedocs(
    repository_url="https://github.com/ploomber/ploomber-engine",
    default_branch="main",
)

###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = "Ploomber"
comments_config = {"hypothesis": False, "utterances": False}
copyright = "2023"
exclude_patterns = ["**.ipynb_checkpoints", ".DS_Store", "Thumbs.db", "_build"]
nb_execution_allow_errors = False
nb_execution_excludepatterns = []
nb_execution_in_temp = True
nb_execution_show_tb = True
nb_execution_timeout = 180
extensions = [
    "sphinx_togglebutton",
    "sphinx_copybutton",
    "myst_nb",
    "jupyter_book",
    "sphinx_thebe",
    "sphinx_comments",
    "sphinx_external_toc",
    "sphinx.ext.intersphinx",
    "sphinx_design",
    "sphinx_book_theme",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx_jupyterbook_latex",
]
external_toc_exclude_missing = False
external_toc_path = "_toc.yml"
html_baseurl = ""
html_favicon = ""
html_logo = "square-no-bg-small.png"
html_sourcelink_suffix = ""
html_theme = "sphinx_book_theme"
html_theme_options = {
    "search_bar_text": "Search this book...",
    "launch_buttons": {
        "notebook_interface": "jupyterlab",
        "jupyterhub_url": "",
        "thebe": False,
        "colab_url": "",
    },
    "path_to_docs": "doc",
    "repository_url": repository_url,
    "repository_branch": repository_branch,
    "analytics": {"google_analytics_id": "G-64QKMLMJY8"},
    "announcement": (
        "Host Voilà and Streamlit apps for free with "
        "<a href='https://www.platform.ploomber.io/register/'>Ploomber Cloud!</a>"
    ),
    "extra_footer": "",
    "home_page_in_toc": True,
    "use_repository_button": True,
    "use_edit_page_button": False,
    "use_issues_button": True,
}
nb_execution_cache_path = ""
nb_execution_mode = "cache"
latex_engine = "pdflatex"
myst_enable_extensions = [
    "colon_fence",
    "dollarmath",
    "linkify",
    "substitution",
    "tasklist",
]
myst_url_schemes = ["mailto", "http", "https"]
myst_heading_anchors = 2
nb_output_stderr = "show"
numfig = True
pygments_style = "sphinx"
suppress_warnings = ["myst.domains"]
use_jupyterbook_latex = True
use_multitoc_numbering = True
